name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}/build
  cancel-in-progress: true

env:
  NODE_VERSION: 22.12.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build iOS App
        run: eas build --non-interactive --platform ios

      - name: Build Android App
        run: eas build --non-interactive --platform android
